### ISSUE TITLE
More test coverage and documentation

### ISSUE THREAD

**Issue by seocahill** [seocahill/ha-postgres-docker-stack#7]
- [ ]  Wal-e (or wal-g) full or PIT recovery
 - [ ]  Disaster recovery (brand new cluster)

**Comment by yayitswei** [comment]
Thanks so much for publishing this stack! It's the cleanest solution I've found so far for an HA Postgres with streaming backups on Docker Swarm. Your documentation is great too, between this repo and the blog posts I was able to understand and set up the test stack.

I'm getting stuck on running the staging stack and configuring wal-e streaming to AWS. I've [filled out the staging.yml file](https://gist.github.com/yayitswei/a9c4a2338132666b5f772f8b508ba6df) and I'm getting this error on the leader node:

```
2018-02-17 06:44:39,737 INFO: Selected new etcd server http://10.0.6.58:2379
2018-02-17 06:44:39,748 INFO: Lock owner: None; I am dbnode1

WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.
2018-02-17 06:44:42,008 INFO: postmaster pid=30
LOG:  database system was shut down at 2018-02-17 06:44:41 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
2018-02-17 06:44:43,044 INFO: establishing a new patroni connection to the postgres cluster
2018-02-17 06:44:43,070 INFO: initialized a new cluster
**ERROR:  replication slot "dbnode3" does not exist**
2018-02-17 06:44:49,748 INFO: Lock owner: dbnode1; I am dbnode1
2018-02-17 06:44:49,776 INFO: no action.  i am the leader with the lock
```

I suppose I could troubleshoot my issue by digging through the patroni documentation, but if you can quickly spot what's wrong I'd appreciate it!

Also, why did you split up the dbnode env files in staging rather than keep them together like in test? As far as I understand the majority of the settings are same.

**Comment by seocahill** [comment]
hi @yayitswei thanks! 

Unfortunately as often happens in webdev my attention has been diverted elsewhere since I wrote these articles. I did at one stage have patroni and wal-e configured but I don't really have the time at the moment to debug this, apologies.

> replication slot "dbnode3" does not exist**

I guess dbnode3's volume must not have access to ```/var/lib/postgresql/data/pg_replslot/```?

> why did you split up the dbnode env files in staging rather than keep them together like in test

No particular reason, just anticipating more granular configuration might be required in staging.

I will try and have a look at this if I can next weekend but I think it would be a good idea to ask the patroni guys for some input. Things are moving quite fast in this space and I'm sure they will have better (and more current) input that I have at the moment.

**Comment by yayitswei** [comment]
No worries, after some more digging it turns out the error is superfluous (https://github.com/zalando/patroni/issues/83). I've also got streaming to S3 working. The only problem I've found is sometimes on cold start HAProxy can't reach the db nodes, and restarting the stack seems to fix it.

Did you end up using this setup for anything in production? If so, curious how it worked and what issues you ran into.

Feel free to close this issue, and all the best with your other pursuits.

**Comment by seocahill** [comment]
> I've also got streaming to S3 working

👍 

> The only problem I've found is sometimes on cold start HAProxy can't reach the db nodes, and restarting the stack seems to fix it.

Yeah there's probably a need for some health checks or restart tweaks in that regard.

> Did you end up using this setup for anything in production? If so, curious how it worked and what issues you ran into.

Not for anything serious - it was more an evaluation situation.  I'd love to dive into this further when I get some spare time in the future though.
